on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC18F4550
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F4550
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/68613061a2c37611b235c63a43954f91
          gist_title: Pr치ctica 3 - Corrimiento de Bits MPLAB X PIC assembler MPASM PIC18F4550
          gist_description: Pr치cticas MPASM
          github_file: Proyecto/PIC18F4550/Corrimiento_Bits.X/corrimiento_bits.asm
          file_encoding: ISO-8859-1
    #PIC18F45K50
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F45K50
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/d55b01182166dcce48cd37303ae3dbef
          gist_title: Pr치ctica 3 - Corrimiento de Bits MPLAB X PIC assembler MPASM PIC18F45K50
          gist_description: Pr치cticas MPASM
          github_file: Proyecto/PIC18F45K50/Corrimiento_Bits.X/corrimiento_bits.asm
          file_encoding: ISO-8859-1